#!/bin/sh

#    WM_COMPILE_OPTION = Opt | Debug | Prof
export WM_COMPILE_OPTION=Opt

cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation

targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

(wmake)

#------------------------------------------------------------------------------
